apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: apimail
  labels:
    app: sendmail
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sendmail
  template:
    metadata:
      labels:
        app: sendmail
    spec:
      containers:
        - name: my-app-sendmail
          image: mdianmareyah/sendemail-github:16
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: dockerhub-secret
